[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/tveco-invoice-generator-bff-1.0.0.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
